require("lazy").setup({
    root = nil,
    -- install = { missing = false, },
    defaults = { version = "*" },
    spec = {
        { import = "plugins.rose-pine" },
        { import = "plugins.telescope" },
        { import = "plugins.web-devicons" },
        { import = "plugins.lualine" },
        { import = "plugins.luasnip" },
        { import = "plugins.vimtex" },
        { import = "plugins.treesitter" },
        { import = "plugins.alpha" },
        { import = "plugins.oil" },
        { import = "plugins.tmux" },
        { import = "plugins.autopairs" },
        { import = "plugins.lsp" },
        { import = "plugins.lspsaga"},
        { import = "plugins.dap"},
        { import = "plugins.otter" },
        { import = "plugins.highlight-color" },
        { import = "plugins.trouble" },
        { import = "plugins.godbolt" },
        { import = "plugins.signature" },
        { import = "plugins.surround" },
        { import = "plugins.dadbod" },
        { import = "plugins.rainbow-delimiters" },
        { import = "plugins.markdown-preview"},
        { import = "plugins.flutter-tools"},
        { import = "plugins.vim-jack-in"},
        { import = "plugins.conjure"},
        { import = "plugins.vim-sexp"},
    }
})

